# Generated by Django 5.2.5 on 2025-08-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='measurement_images/', verbose_name='Снимок'),
        ),
    ]
